name: build

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch full history
        filter: tree:0
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      run: |
        make docker-build 

    - name: Push docker image
      run: |
        make docker-push 